"""V2 structured schema models for DeepRoute.

These Pydantic models define the JSON schema for the structured routing
system. Generated by Opus during dr_init, consumed programmatically by
dr_lookup/dr_search in schema mode (zero LLM calls).
"""

from __future__ import annotations

from pydantic import BaseModel, Field

SCHEMA_VERSION = "2.0.0"


# --- Manifest (top-level index) ---

class TechStackEntry(BaseModel):
    category: str  # language, framework, database, infra, ci, tool
    name: str
    version: str = ""


class ModuleRef(BaseModel):
    name: str              # e.g. "src/deeproute"
    summary: str           # 1 sentence
    tags: list[str] = Field(default_factory=list)
    primary_language: str = ""
    file_count: int = 0


class Manifest(BaseModel):
    schema_version: str = SCHEMA_VERSION
    project_name: str = ""
    description: str = ""
    tech_stack: list[TechStackEntry] = Field(default_factory=list)
    modules: list[ModuleRef] = Field(default_factory=list)
    conventions: list[str] = Field(default_factory=list)
    tree_summary: str = ""
    generated_at: str = ""
    generated_by: str = ""
    has_notes: bool = False
    drift_score: float = 0.0
    last_factual_update: str = ""
    has_embeddings: bool = False
    workspace_complexity: str = ""  # low, medium, high
    recommended_init_model: str = ""
    recommended_update_model: str = ""


# --- Module detail ---

class ParamSpec(BaseModel):
    name: str
    type: str = ""
    default: str = ""
    description: str = ""


class FunctionSpec(BaseModel):
    name: str
    file: str = ""
    line: int = 0
    params: list[ParamSpec] = Field(default_factory=list)
    return_type: str = ""
    description: str = ""
    tags: list[str] = Field(default_factory=list)
    is_public: bool = True
    source: str = "llm"  # "ast", "llm", or "merged"
    decorators: list[str] = Field(default_factory=list)
    is_async: bool = False


class ClassSpec(BaseModel):
    name: str
    file: str = ""
    line: int = 0
    description: str = ""
    bases: list[str] = Field(default_factory=list)
    key_methods: list[FunctionSpec] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    source: str = "llm"  # "ast", "llm", or "merged"


class FileRole(BaseModel):
    path: str
    role: str = ""
    tags: list[str] = Field(default_factory=list)
    classes: list[str] = Field(default_factory=list)
    functions: list[str] = Field(default_factory=list)


class ModuleDependency(BaseModel):
    module: str
    relationship: str = ""  # imports, calls, extends
    description: str = ""


class CommonTask(BaseModel):
    task: str
    steps: str


class ComplexityInfo(BaseModel):
    score: int = 0  # 1-10
    factors: list[str] = Field(default_factory=list)
    file_count: int = 0
    function_count: int = 0
    class_count: int = 0
    public_functions: int = 0
    avg_params: float = 0.0
    max_params: int = 0
    import_count: int = 0
    cross_module_deps: int = 0
    directory_depth: int = 0
    async_ratio: float = 0.0


class ModelHintsInfo(BaseModel):
    analysis: str = "sonnet"
    update: str = "sonnet"
    query: str = "haiku"


class ModuleSchema(BaseModel):
    schema_version: str = SCHEMA_VERSION
    name: str = ""
    path: str = ""
    summary: str = ""
    purpose: str = ""
    tags: list[str] = Field(default_factory=list)
    files: list[FileRole] = Field(default_factory=list)
    classes: list[ClassSpec] = Field(default_factory=list)
    functions: list[FunctionSpec] = Field(default_factory=list)
    dependencies: list[ModuleDependency] = Field(default_factory=list)
    common_tasks: list[CommonTask] = Field(default_factory=list)
    notes_file: str = ""
    drift_score: float = 0.0
    last_factual_update: str = ""
    complexity: ComplexityInfo = Field(default_factory=ComplexityInfo)
    model_hints: ModelHintsInfo = Field(default_factory=ModelHintsInfo)


# --- Interfaces ---

class HTTPEndpoint(BaseModel):
    method: str = ""
    path: str = ""
    handler: str = ""  # file:function
    description: str = ""
    request_body: str = ""
    response: str = ""
    tags: list[str] = Field(default_factory=list)


class GRPCService(BaseModel):
    name: str = ""
    proto_file: str = ""
    methods: list[str] = Field(default_factory=list)
    description: str = ""


class EventHandler(BaseModel):
    event: str = ""
    handler: str = ""
    source: str = ""
    description: str = ""


class CLICommand(BaseModel):
    name: str = ""
    description: str = ""
    handler: str = ""


class InterfaceSchema(BaseModel):
    schema_version: str = SCHEMA_VERSION
    http_endpoints: list[HTTPEndpoint] = Field(default_factory=list)
    grpc_services: list[GRPCService] = Field(default_factory=list)
    event_handlers: list[EventHandler] = Field(default_factory=list)
    cli_commands: list[CLICommand] = Field(default_factory=list)


# --- Config files ---

class DockerStage(BaseModel):
    name: str = ""
    base_image: str = ""
    purpose: str = ""


class CIStep(BaseModel):
    name: str = ""
    trigger: str = ""
    actions: list[str] = Field(default_factory=list)


class ComposeService(BaseModel):
    name: str = ""
    image: str = ""
    build: str = ""
    ports: list[str] = Field(default_factory=list)
    depends_on: list[str] = Field(default_factory=list)
    purpose: str = ""


class ConfigFileSummary(BaseModel):
    file: str = ""
    type: str = ""  # dockerfile, docker-compose, ci, terraform, pyproject
    summary: str = ""


class ConfigFilesSchema(BaseModel):
    schema_version: str = SCHEMA_VERSION
    files: list[ConfigFileSummary] = Field(default_factory=list)
    docker_stages: list[DockerStage] = Field(default_factory=list)
    compose_services: list[ComposeService] = Field(default_factory=list)
    ci_pipelines: list[CIStep] = Field(default_factory=list)


# --- Patterns ---

class DetectedPattern(BaseModel):
    name: str = ""
    category: str = ""  # architectural, structural, behavioral
    locations: list[str] = Field(default_factory=list)
    description: str = ""
    tags: list[str] = Field(default_factory=list)


class PatternsSchema(BaseModel):
    schema_version: str = SCHEMA_VERSION
    patterns: list[DetectedPattern] = Field(default_factory=list)
